# ********************************************************************
# * Licensed Materials - Property of HCL                             *
# *                                                                  *
# * Copyright HCL Technologies Ltd. 2024. All Rights Reserved.       *
# *                                                                  *
# * Note to US Government Users Restricted Rights:                   *
# *                                                                  *
# * Use, duplication or disclosure restricted by GSA ADP Schedule    *
# ********************************************************************

parameters:
  - name: "INSTANCE_TYPE"
    optional: true
    description: "Type of EC2 instance used."
    default: "t3a.small"
  - name: "INSTANCE_NAME"
    optional: true
    description: "Instance name, used for route53 name and tagging in AWS."
    default: ""
  - name: "HOSTED_ZONE"
    optional: true
    description: "Hosted zone used for route53 entry."
    default: "Z3OEC7SLEHQ2P3"
  - name: "DOMAIN_SUFFIX"
    optional: true
    description: "Domain suffix used for route53 creation."
    default: ".team-q-dev.com"
  - name: "INSTANCE_OWNER"
    optional: true
    description: "Owner tagged to the EC2 instance."
    default: "philipp.milich@hcl.com"
  - name: "EXECUTION_MODE"
    optional: true
    description: "Determines if server should be created or destroyed, accepts either CREATE or DESTROY"
    default: "CREATE"
  - name: "AWS_SUBNET_NAME"
    optional: true
    description: "Target AWS Subnet to deploy into"
    default: "Dev02"
  - name: "KUBE_DEPLOY_JOB"
    optional: true
    description: "A job to deploy in native-kube environment"
    default: "CI/kube-deploy/native-kube-next-deploy"
