apiVersion: v1
kind: PersistentVolume
metadata:
  name: PV_NAME
  labels:
    type: local
    ADDITIONAL_LABEL
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "WORKING_DIRECTORY"
