# ********************************************************************
# * Licensed Materials - Property of HCL                             *
# *                                                                  *
# * Copyright HCL Technologies Ltd. 2024. All Rights Reserved.       *
# *                                                                  *
# * Note to US Government Users Restricted Rights:                   *
# *                                                                  *
# * Use, duplication or disclosure restricted by GSA ADP Schedule    *
# ********************************************************************

parameters:
  - choice:
    name: 'CLUSTER_MANAGER_MODE'
    optional: true
    choices:
      - 'None'
      - 'Create'
      - 'Destroy'
    default: "None"
    description: 'Select the action to perform: Create,Destroy or No-Action (None) on a given instance as per your needs.'
  - name: "CLUSTER_NAME"
    optional: true
    description: "Name of the EKS cluster"
    default: "eks-cluster-dx01"
  - name: "CLUSTER_REGION"
    optional: true
    description: "AWS region where the EKS cluster will be deployed"
    default: "us-east-1"
  - name: "VPC_ID"
    optional: true
    description: "ID of the VPC where the EKS cluster will be deployed"
    default: "vpc-0a5b5af3ec875492d"
  - name: "SUBNETS"
    optional: true
    description: "Comma-separated list of subnet IDs for the EKS cluster"
    default: "subnet-0a2fc24d57d19c31b, subnet-0f5af81d4a148c527"
  - name: "NODE_GROUP_NAME"
    optional: true
    description: "Name of the node group"
    default: "eks-nodes-dx01"
  - name: "NODE_INSTANCE_TYPE"
    optional: true
    description: "Instance type for the worker nodes"
    default: "t3.xlarge"
  - name: "DESIRED_WORKER_NODES"
    optional: true
    description: "Number of desired worker nodes"
    default: "1"
  - name: "KUBERNETES_VERSION"
    optional: true
    description: "Kubernetes version number"
    default: "1.28"
  - name: "RESOURCE_TAG_TERM_FLAG"
    optional: true
    description: "Tag term flag for the resources"
    default: "N"
  - name: "RESOURCE_TAG_AREA"
    optional: true
    description: "Tag area for the resources"
    default: "INFRA"
  - name: "RESOURCE_TAG_OWNER"
    optional: true
    description: "Tag owner for the resources"
    default: "nitin.jagjivan@hcl.com"
  - name: "RESOURCE_TAG_SAVINGS"
    optional: true
    description: "Savings tag required by central infrastructure team"
    default: "POPO_Manual"
