parameters:
  - name: "APP_GIT_REPOS"
    default: "RingAPI, image-processor, media-library"
    description: "Repositories from applications that are not Core."
    optional: true
  - name: "CORE_COMPONENTS"
    default: "pzn, wcm-v2, access, remotemodel, search, users"
    description: "Core components with API specs"
    optional: true
  - name: "HCL_DX_GITHUB_HOST"
    default: "git@github.com:HCL-TECH-SOFTWARE"
    description: "Github host for documentation push"
    optional: true
  - name: "REPOSITORY_NAME"
    default: "experience-api-documentation"
    description: "HCL-DX Github Experience API Documentation"
    optional: true
  - name: "ENV_TAG_RING_API"
    default: "95_CF207"
    description: "RingAPI branch and tag"
  - name: "ENV_TAG_DAM_API"
    default: "95_CF207"
    description: "DAM branch and tag"
  - name: "ENV_TAG_IP_API"
    default: "95_CF207"
    description: "Image-Processor branch and tag"
  - name: "ENV_TAG_PZN_API"
    default: "95_CF207"
    description: "PZN branch and tag"
  - name: "ENV_TAG_WCMV2_API"
    default: "95_CF207"
    description: "WCM v2 branch and tag"
  - name: "ENV_TAG_ACCESS_API"
    default: "95_CF207"
    description: "Access Control branch and tag"
  - name: "ENV_TAG_REMOTEMODEL_API"
    default: "95_CF207"
    description: "Remote Model branch and tag"
  - name: "ENV_TAG_SEARCH_API"
    default: "95_CF207"
    description: "Search branch and tag"
  - name: "ENV_TAG_USERS_API"
    default: "95_CF207"
    description: "Users branch and tag"
  - name: "HCL_DX_GITHUB_CREDENTIAL_ID"
    default: "public-git-credentials"
    description: "Credential ID used in Jenkins to push the changes"
    optional: true
