{
 "title": "Jenkins Health",
 "description": "Jobs queue speeds and rates, Executors availability, Nodes status, Jenkins and JVM resource usage.",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Processing speed",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(jenkins_job_building_duration_count[1m])"
    }
   ]
  },
  {
   "title": "Job queue duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_job_queuing_duration" }
   ]
  },
  {
   "title": "Queued rate",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(jenkins_job_queuing_duration_count[1m])"
    }
   ]
  },
  {
   "title": "JVM free memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(vm_memory_total_max{job=\"jenkins\"} - vm_memory_total_used{job=\"jenkins\"}) / vm_memory_total_max{job=\"jenkins\"} * 100.0"
    }
   ]
  },
  {
   "title": "JVM uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "vm_uptime_milliseconds{job=\"jenkins\"}"
    }
   ]
  },
  {
   "title": "Jenkins health",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_health_check_score" }
   ]
  },
  {
   "title": "Jenkins plugins failed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_plugins_failed" }
   ]
  },
  {
   "title": "Jenkins nodes offline",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_node_offline_value" }
   ]
  },
  {
   "title": "Jenkins queue size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_queue_size_value" }
   ]
  },
  {
   "title": "Executor free",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_executor_free_value" }
   ]
  },
  {
   "title": "Executors health",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 4, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(jenkins_job_building_duration_sum/jenkins_job_building_duration_count)"
    }
   ]
  },
  {
   "title": "Executor In-use",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_executor_in_use_value" }
   ]
  },
  {
   "title": "Resource usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "vm_cpu_load{job=\"jenkins\"}"
    }
   ]
  }
 ]
}