apiVersion: v1
kind: PersistentVolume
metadata:
  name: PV
spec:
  storageClassName: dx-deploy-stg
  capacity:
    storage: 100Gi 
  accessModes:
  - ReadWriteMany
  nfs: 
    path: NFS_PATH/PV
    server: NFS_PRIVATE_HOST_NAME
  persistentVolumeReclaimPolicy: Retain
